- name: Deploy PROD
  run: |
    ssh -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
    set -e
    cd /opt/avqon-prod/antivirus-core
    git fetch origin
    git checkout main
    git pull origin main
    sudo systemctl restart avqon-backend-prod
    echo "PROD deploy done"
    EOF
