echo "===> Update PROD code"
cd /opt/avqon-prod
git fetch origin
git checkout main
git reset --hard origin/main

echo "===> Restart backend"
sudo systemctl restart avqon-backend

echo "===> PROD deployment finished successfully"
